apiVersion: v1
kind: Service
metadata:
  name: school-management-service
  labels:
    app: school-management-web
spec:
  selector:
    app: school-management-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
