name: Build and Export Docker Image

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: 

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t school-management-web:latest .
          docker save -o school-management-web.tar school-management-web:latest

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: school-management-web.tar
          retention-days: 5
